# Generated by Django 5.1.4 on 2024-12-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointer', '0003_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.TimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
